default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.409
    hooks:
      - id: pyright
        exclude: ^experimentation/

  - repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v5.1.0
    hooks:
      - id: complexipy
        types_or: [python, pyi]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.0.0
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.0.0"]
