"""Shared constants."""

COMMON_REQUIRED_KEYS = ("uri", "did", "created_at")

POST_REQUIRED_KEYS = COMMON_REQUIRED_KEYS
LIKE_REQUIRED_KEYS = (*COMMON_REQUIRED_KEYS, "subject_uri")
REPOST_REQUIRED_KEYS = LIKE_REQUIRED_KEYS
FOLLOW_REQUIRED_KEYS = (*COMMON_REQUIRED_KEYS, "subject_did")
