DEFAULT_REGION = "us-east-2"
DEFAULT_DATABASE = "lab_data_integrations_interface"
DEFAULT_WORKGROUP = "lab-data-integrations-interface"
OLAP_WORKGROUP = "lab-data-integrations-interface-olap"
S3_BUCKET = "lab-data-integrations-interface"
