DEFAULT_REGION = "us-east-2"
DEFAULT_DATABASE = "lab_data_integrations_interface"
DEFAULT_WORKGROUP = "lab-data-integrations-interface"
OLAP_WORKGROUP = "lab-data-integrations-interface-olap"
S3_BUCKET = "lab-data-integrations-interface"
PIPELINE_RUNS_TABLE = "lab-data-integrations-interface-pipeline-runs"
CURSOR_BACKUP_TABLE = "lab-data-integrations-interface-cursor-backups"
JETSTREAM_CURSOR_BACKUP_KEY = "bluesky_jetstream_cursor_latest"
